### ISSUE TITLE
White line on cursor

### ISSUE THREAD

**Issue by DerpDerpling** [antiden/macOS-cursors-for-Windows#3]
![chrome_KMODLjU06z](https://user-images.githubusercontent.com/57187871/106357931-3749b480-62d7-11eb-9720-aa5f1830fddd.png)
im having an issue where there is a white line on my cursor... any idea why its happening?

**Comment by antiden** [comment]
> ![chrome_KMODLjU06z](https://user-images.githubusercontent.com/57187871/106357931-3749b480-62d7-11eb-9720-aa5f1830fddd.png)
> im having an issue where there is a white line on my cursor... any idea why its happening?

What's the problem?

**Comment by AbhigyanRanjan0505** [comment]
Can't understand the problem

**Comment by AbhigyanRanjan0505** [comment]
Ok, I think that is its design because the tail is a little curve when you zoom too much and the line is sooooo small that it's ignorable until you just zoom a lot.

**Comment by AbhigyanRanjan0505** [comment]
![Curve](https://user-images.githubusercontent.com/71014464/107110082-09321a80-686b-11eb-9e07-bb083a9e8c48.png)
- This is the curve
![Issue](https://user-images.githubusercontent.com/71014464/107110091-236bf880-686b-11eb-8ac1-f2eb2a36ecbc.png)
- If you see carefully at the lower part you see a little line on the black part of the cursor.

I think that this is the problem but I don't understand what this issue is really about.
